@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI3ZmQ5MjFiNC0wYjJiLTRhZmEtOWJkYi1lNTI5MDU5MTM1MzciLCJlbWFpbCI6ImFkbUBnbWFpbC5jb20iLCJpYXQiOjE3ODMzNjM2MzEsImV4cCI6MTc4MzM3MDgzMX0.PpemhALKGcri6mkY-SvchYZntGzUmsmP9yXbzbMoHoY



###
// STATUS OK

GET http://localhost:3005/health



####
//Mostra os Usuários

GET http://localhost:3005/users
Authorization: Bearer {{token}}



###
//Cria o usuário

POST http://localhost:3005/users
Content-Type: application/json

{
  "nickname": "adm",
  "email": "adm@gmail.com",
  "password": "admin123",
  "role": "ADMIN"
}



###
//Atualiza Usuário

PUT http://localhost:3005/products/762b2c54-6bab-49e1-8d16-dafd3598e4e7
Content-type: application/json
Authorization: Bearer {{token}}

{
  "nickname": "viado",
  "email": "viado@gmail.com",
  "password": "viado123"
}



###
//Pede o token do usuário

POST http://localhost:3005/auth/login
Content-Type: application/json

{
  "email": "adm@gmail.com",
  "password": "admin123"
}



###
//Deleta usuário

DELETE http://localhost:3005/users/4
Authorization: Bearer {{token}}



###
//Cria Produto

POST http://localhost:3005/products
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "name": "Chave Comum",
  "categoryId": "8bfc8bf7-d385-4cf4-8617-0913f1cb82c8",
  "description": "Chave Comum (chaves para abrir a Caixa Comum do servidor)",
  "price": 0.50,
  "image": "",
  "available": true,
  "tag": "Bom",
  "rating": 5
}



###
//Ver Produtos

GET http://localhost:3005/products
Content-Type: application/json
Authorization: Bearer {{token}}



###
//Atualiza Produtos

PUT http://localhost:3005/products/762b2c54-6bab-49e1-8d16-dafd3598e4e7
Content-type: application/json
Authorization: Bearer {{token}}

{
  "name": "Vip Imperador",
  "categoryId": "3108208f-74b4-426a-a5c2-ee678fc91a60",
  "description": "Vip Lord com itens dentro do jogo e tag especial",
  "price": 49.90,
  "image": "",
  "available": true,
  "tag": "Mais Pedido",
  "rating": 10
}



###
//Cria Categoria

POST http://localhost:3005/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "label": "chaves",
  "icon": "image"
}



###
//Ver Categorias

GET http://localhost:3005/categories
Content-Type: application/json
Authorization: Bearer {{token}}

{
  "label": "chaves",
  "icon": "image"
}

