@token = eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiI0IiwiZW1haWwiOiJhcnRodXJAZ21haWwuY29tIiwiaWF0IjoxNzgyMjQzNDgxLCJleHAiOjE3ODIyNTA2ODF9.sAz2YcU8U2jpnktTn9lOCk7whjtYBbgD1dTvnib0Dq8

###
// STATUS OK
GET http://localhost:3005/health


####
GET http://localhost:3005/users
Authorization: Bearer {{token}}

###

//Cria o usuário
POST http://localhost:3005/users
Content-Type: application/json

{
  "nickname": "viado",
  "email": "viado@gmail.com",
  "password": "viado123"
}

//Pede o token do usuário
###
POST http://localhost:3005/auth/login
Content-Type: application/json

{
  "email": "arthur@gmail.com",
  "password": "arthur123"
}

###

//Deleta usuário
DELETE http://localhost:3005/users/4
Authorization: Bearer {{token}}

###
//Cria um usuário

